const actionNames = {
  GET_QUESTIONS: "GET_QUESTION",
  CHANGE_CURRENT_QUESTION: "CHANGE_CURRENT_QUESTION",
  CHANGE_PROGRESS: "CHANGE_PROGRESS",
  OPEN_COMPLETE_DIALOG: "OPEN_COMPLETE_DIALOG",
  SUBMIT_RESULT: "SUBMIT_RESULT",
  OPTION_CLICKED: "OPTION_CLICKED",
  CHANGE_LOADING: "CHANGE_LOADING",
  CHANGE_THEME: "CHANGE_THEME",
  GET_LIST: "GET_LIST",
  SET_TEST_NUMBER: "SET_TEST_NUMBER",
};

export default actionNames;
